config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:update, :show, :index]
  resources :advertisements 

   resources :topics do
     resources :posts, except: [:index], controller: 'topics/posts' #Otherwise it would have used the posts controller, which we are now using to display a list of favorite community posts. 
   end
 
   resources :posts, only: [:index] do
     resources :comments, only: [:new, :create, :destroy]
     resources :favorites, only: [:create, :destroy]
     resources :summaries
     post '/up-vote' => 'votes#up_vote', as: :up_vote
     post '/down-vote' => 'votes#down_vote', as: :down_vote
   end

  get 'contact' => 'welcome#contact' 
  get 'about' => 'welcome#about' # allowing a user to type /about rather than /welcome/about.

  root to: 'welcome#index'
  

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  include ViewHelper
  has_many :posts, dependent: :destroy 
  validates :name, length: { minimum: 5 }, presence: true
  mount_uploader :image, ImageUploader

  scope :visible_to, -> (user) { user ? all : where(public: true) } 
  scope :publicly_viewable, -> {where(public: true) } 
  scope :privately_viewable, -> {where(public: false) } 
  # Calling the scope invokes the result of its lambda on the collection 
  # or class on which it was originally called. 
  # So this scope returns the equivalent of topic_collection.all 
  # or topic_collection.where(public: true), depending on the value of user.
end

app/controllers/topics/posts_controller.rb
class Topics::PostsController < ApplicationController
  #Topics::PostsController instructs the controller where to find the appropriate views to invoke. 
  #See the Admin::UserPermissions example in the Rails Guide.

  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  #skip_before_action :flash_attack, only: [:new, :index]
  # def index
  #   @posts = policy_scope(Post)
  # end

  def show
    @post = Post.find(params[:id])
    @topic = Topic.find(params[:topic_id]) #Why do we find the Post by :id and the Topic by :topic_id? That's what our rake routes output says it's expecting: /topics/:topic_id/posts/:id/edit. Rails conventions make the params hash consistent with these expectations.
    @summary = @post.summary
    @comments = @post.comments
    authorize @comments
    authorize @topic

  end

  def new
    @topic = Topic.find(params[:topic_id])
     #authorize method comes from Pundit in the ApplicationController. 
    @post = Post.new
    authorize @post
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post 
  end

  def update 
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post
    if @post.update_attributes(post_params)
      flash[:notice] = "Post was updated."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :edit
    end 
  end 

 def create
   @topic = Topic.find(params[:topic_id])
   @post = current_user.posts.build(post_params)
   @post.topic = @topic 
   authorize @post 
   if @post.save_with_initial_vote
       flash[:notice] = "Post was saved with an upboat."
       redirect_to [@topic, @post]
   else
     flash[:error] = "There was an error saving the post. Please try again."
     render :new
   end
 end

 def destroy
     @topic = Topic.find(params[:topic_id])
     @post = Post.find(params[:id])
     authorize @post
 
     if @post.destroy
       flash[:notice] = "\"#{@post.title}\" was deleted successfully."
       redirect_to @topic
     else
       flash[:error] = "There was an error deleting the post."
       render :show
     end
   end


 private

  

  def post_params
    params.require(:post).permit(:title, :body, :image)
  end


end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
    @topics = Topic.visible_to(current_user).paginate(page: params[:page], per_page: 10)
    authorize @topics 
    # @current_page = (params[:offset].to_i/PER_PAGE).to_i 
    #the scope returns an Active Record relation.
  end

  def new
    @topic = Topic.new
    authorize @topic 
  end

  def show

    @topic = Topic.find(params[:id])
    authorize @topic 
    @posts = @topic.posts.includes(:user).includes(:comments).paginate(page: params[:page], per_page: 10)
  end

  def edit
    @topic = Topic.find(params[:id])
    authorize @topic 
  end

   def create
   @topic = Topic.new(topic_params)
   authorize @topic
   if @topic.save
     redirect_to @topic, notice: "Topic was saved successfully."
   else
     flash[:error] = "Error creating topic. Please try again."
     render :new
   end
  end 
 
   def update
     @topic = Topic.find(params[:id])
     authorize @topic
     if @topic.update_attributes(topic_params)
       redirect_to @topic
     else
       flash[:error] = "Error saving topic. Please try again."
       render :edit
     end
   end

   def destroy 
    @topic = Topic.find(params[:id])
    authorize @topic
     if @topic.destroy
       flash[:notice] = "\"#{@topic.name}\" was deleted successfully."
       redirect_to topics_path
     else
       flash[:error] = "There was an error deleting the topic."
       render :show
     end
   end 

   private 

    def topic_params
      params.require(:topic).permit(:name, :description, :public, :image)
    end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for topic do |f| %>
<div class="col-md-8">
   <% if topic.errors.any? %>
     <div class="alert alert-danger">
       <h3>There are <%= pluralize(topic.errors.count, "error") %>.</h3> <!-- errors method checks topic based on validations in topic.rb --> 
       <ul>
         <% topic.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
   <% end %>
       <%= form_group_tag(topic.errors[:name]) do %>
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
       <% end %>
       </div>
       <div class="form-group">
         <%= f.label :description %>
         <%= f.text_field :description, class: 'form-control', placeholder: "Enter topic description" %>
       </div>
       <% if topic.image? %>
         <div class="form-group">
           <p>Current image</p>
           <%= image_tag(@topic.image.profile.url)%>
         </div>
       <% end %>
       <div class="form-group">
         <%= f.label :image %>
         <%= f.file_field :image %>
         <%= f.hidden_field :image_cache %>
       </div>
       <div class="form-group">
         <%= f.label :public, class: 'checkbox' do %>
           <%= f.check_box :public %> Public topic
         <% end %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>

app/views/topics/edit.html.erb
<h1>New Topic</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>You're editing a topic? Crazy.</p>
     <ul>
       <li>Editing a topic requires page refresh. WTF?. <%= @topic.name %> </li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= render partial: 'form', locals: { topic: @topic} %>
   </div>
 </div>
</div>

app/views/topics/index.html.erb
<h1>Topics</h1>

<div class="row">
  <div class="col-md-8">

    <% @topics.each do |topic| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to topic.name, topic %>
          </h4>
          <small>
            <%= topic.description %>
          </small>
        </div>
      </div>
    <% end %>
    <%= will_paginate @topics %>
  </div>

  <div class="col-md-4">
    <% if policy(Topic.new).create? %>
      <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for topics</p>
     <ul>
       <li>Go nuts. Must be over 5 characters to ride. </li>
     </ul>
   </div>
    <%= render partial: 'form', locals: { topic: @topic} %>
 </div>

app/views/topics/show.html.erb
 
<div class="row text-center">
</div>
<div class="row text-center">
  <h1><%= @topic.name %></h1>
</div>
<div class="row text-center">
<% if @topic.image? %>
  <div class="col-md-12 center">
  <%= image_tag(@topic.image.full.url) %> 
  </div>
<% end %>

</div>

 
 <% if policy(@topic).update? %>
   <%= link_to "Edit Topic", edit_topic_path(@topic), class: 'btn btn-success' %>
 <% end %>
 
 <div class="row">
   <div class="col-md-8">
     <p ><%= @topic.description %></p>
      <%= render @posts %><!-- THIS IS WHERE POSTS EACH USED TO BE  -->
   </div>
   <div class="col-md-4">
     <% if policy(Post.new).create? %>
       <%= link_to "New Post", new_topic_post_path(@topic), class: 'btn btn-success' %>
     <% end %>
     <% if policy(@topic).destroy? %>
       <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' } %> 
     <% end %>
   </div>
 </div>