config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:update, :show, :index]
  resources :advertisements 

   resources :topics do
     resources :posts, except: [:index], controller: 'topics/posts' #Otherwise it would have used the posts controller, which we are now using to display a list of favorite community posts. 
   end
 
   resources :posts, only: [:index] do
     resources :comments, only: [:new, :create, :destroy]
     resources :favorites, only: [:create, :destroy]
     resources :summaries
     post '/up-vote' => 'votes#up_vote', as: :up_vote
     post '/down-vote' => 'votes#down_vote', as: :down_vote
   end

  get 'contact' => 'welcome#contact' 
  get 'about' => 'welcome#about' # allowing a user to type /about rather than /welcome/about.

  root to: 'welcome#index'
  

end

app/models/post.rb
class Post < ActiveRecord::Base


  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy 
  has_one :summary, dependent: :destroy 
  has_many :favorites, dependent: :destroy 
  belongs_to :user
  belongs_to :topic


  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :topic, presence: true #This is throwing an error, which is odd.
  validates :user, presence: true


  #default_scope { order('created_at DESC') }
  default_scope { order('rank ASC') } #Highest ranked posts go first
  scope :ordered_by_reverse_created_at, -> { order('created_at ASC') }
  scope :ordered_by_title,              -> { order('title ASC') }

  mount_uploader :image, ImageUploader



  def markdown_title
    render_as_markdown(title)
  end

  def markdown_body
    render_as_markdown(body)
  end

  def up_votes
    votes.where(value: 1).count
  end

  def down_votes
    votes.where(value: -1).count
  end

  def points
    up_votes - down_votes 
  end

  def age
    age_in_days = (self.created_at - Time.new(1970,1,1)) / (60 * 60 * 24) # 1 day in seconds
  end 

  def update_rank
   
   new_rank = points - age/1000  #Higher ranked posts go first. This ranking makes no sense.
   update_attribute(:rank, new_rank)
  end

  def create_vote
    user.votes.create(post: self, value: 1)
  end 

  def save_with_initial_vote
    ActiveRecord::Base.transaction do
       self.create_vote
       self.save
    end 
  end 


  private 
  
  def render_as_markdown(markdown)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render markdown).html_safe
  end 
end



#There are numerous types of validations. The most common are presence, length, and format. Formatting usually requires a Regex, which is an advanced topic that will be covered later. Here's the Rails Guide on validations - it's a good reference.

app/models/topic.rb
class Topic < ActiveRecord::Base
  include ViewHelper
  has_many :posts, dependent: :destroy 
  validates :name, length: { minimum: 5 }, presence: true
  mount_uploader :image, ImageUploader

  scope :visible_to, -> (user) { user ? all : where(public: true) } 
  scope :publicly_viewable, -> {where(public: true) } 
  scope :privately_viewable, -> {where(public: false) } 
  # Calling the scope invokes the result of its lambda on the collection 
  # or class on which it was originally called. 
  # So this scope returns the equivalent of topic_collection.all 
  # or topic_collection.where(public: true), depending on the value of user.
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   def index
     @topics = Topic.visible_to(current_user)
     @posts = Post.where("posts.created_at > ?", 5.days.ago).paginate(page: params[:page], per_page: 10)
   end
 end

app/controllers/topics/posts_controller.rb
class Topics::PostsController < ApplicationController
  #Topics::PostsController instructs the controller where to find the appropriate views to invoke. 
  #See the Admin::UserPermissions example in the Rails Guide.

  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  #skip_before_action :flash_attack, only: [:new, :index]
  # def index
  #   @posts = policy_scope(Post)
  # end

  def show
    @post = Post.find(params[:id])
    @topic = Topic.find(params[:topic_id]) #Why do we find the Post by :id and the Topic by :topic_id? That's what our rake routes output says it's expecting: /topics/:topic_id/posts/:id/edit. Rails conventions make the params hash consistent with these expectations.
    @summary = @post.summary
    @comments = @post.comments
    authorize @comments
    authorize @topic

  end

  def new
    @topic = Topic.find(params[:topic_id])
     #authorize method comes from Pundit in the ApplicationController. 
    @post = Post.new
    authorize @post
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post 
  end

  def update 
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post
    if @post.update_attributes(post_params)
      flash[:notice] = "Post was updated."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :edit
    end 
  end 

 def create
   @topic = Topic.find(params[:topic_id])
   @post = current_user.posts.build(post_params)
   @post.topic = @topic 
   authorize @post 
   if @post.save_with_initial_vote
       flash[:notice] = "Post was saved with an upboat."
       redirect_to [@topic, @post]
   else
     flash[:error] = "There was an error saving the post. Please try again."
     render :new
   end
 end

 def destroy
     @topic = Topic.find(params[:topic_id])
     @post = Post.find(params[:id])
     authorize @post
 
     if @post.destroy
       flash[:notice] = "\"#{@post.title}\" was deleted successfully."
       redirect_to @topic
     else
       flash[:error] = "There was an error deleting the post."
       render :show
     end
   end


 private

  

  def post_params
    params.require(:post).permit(:title, :body, :image)
  end


end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
    @topics = Topic.visible_to(current_user).paginate(page: params[:page], per_page: 10)
    authorize @topics 
    # @current_page = (params[:offset].to_i/PER_PAGE).to_i 
    #the scope returns an Active Record relation.
  end

  def new
    @topic = Topic.new
    authorize @topic 
  end

  def show

    @topic = Topic.find(params[:id])
    authorize @topic 
    @posts = @topic.posts.includes(:user).includes(:comments).paginate(page: params[:page], per_page: 10)
  end

  def edit
    @topic = Topic.find(params[:id])
    authorize @topic 
  end

   def create
   @topic = Topic.new(topic_params)
   authorize @topic
   if @topic.save
     redirect_to @topic, notice: "Topic was saved successfully."
   else
     flash[:error] = "Error creating topic. Please try again."
     render :new
   end
  end 
 
   def update
     @topic = Topic.find(params[:id])
     authorize @topic
     if @topic.update_attributes(topic_params)
       redirect_to @topic
     else
       flash[:error] = "Error saving topic. Please try again."
       render :edit
     end
   end

   def destroy 
    @topic = Topic.find(params[:id])
    authorize @topic
     if @topic.destroy
       flash[:notice] = "\"#{@topic.name}\" was deleted successfully."
       redirect_to topics_path
     else
       flash[:error] = "There was an error deleting the topic."
       render :show
     end
   end 

   private 

    def topic_params
      params.require(:topic).permit(:name, :description, :public, :image)
    end

end

app/helpers/posts_helper.rb
module PostsHelper

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/posts/_form.html.erb
<%= form_for [topic, post] do |f| %>
   <% if post.errors.any? %>
     <div class="alert alert-danger">
       <h3>There are <%= pluralize(post.errors.count, "error") %>.</h3> <!-- errors method checks post based on validations in post.rb --> 
       <ul>
         <% post.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
   <% end %>
   <%= form_group_tag(post.errors[:title]) do %>
     <%= f.label :title %>
     <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
   <% end %>
   <% if post.image? %>
         <div class="form-group">
           <p>Current image</p>
           <%= image_tag(post.image.profile.url)%>
         </div>
       <% end %>
   <div class="form-group">
     <%= f.label :image %>
     <%= f.file_field :image %>
     <%= f.hidden_field :image_cache %>
   </div>
   <%= form_group_tag(post.errors[:body]) do %>
     <%= f.label :body %>
     <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
   <% end %>
   <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>
   </div>
 <% end %>



 <!-- Not using instance variables here because topic and post passed in by render partial: 'form', locals: { topic: @topic, post: @post } in edit.html.erb. This partial, because it's part of posts and therefore controlled by the posts controller, does have access to the instance variables, but we're using local variables because we want to be able to use this partial outside of the posts controller.--> 

app/views/topics/posts/edit.html.erb
<h1>Edit Post</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for posts</p>
     <ul>
       <li><%= @topic.name %> Make sure it rhymes.</li>
       <li><%= @post.title %></li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
   </div>
 </div>

app/views/topics/posts/new.html.erb
<h1>New Post</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for posts</p>
     <ul>
       <li>Topic name is: <%=@topic.name %> </li> 
       <li><%= @post.title %></li>
     </ul>
   </div>
   <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
 </div>

app/views/topics/posts/show.html.erb
<div class="row">
  <div class="col-md-2">
    <% if policy(Post.new).edit? %> 
  <%= link_to "Edit post", edit_topic_post_path(@topic,@post), class: 'btn btn-success' %> 
  <% end %> 
  </div>
  <div class="col-md-2">
    <% if policy(@post).destroy? %>
       <%= link_to "Delete Post", [@topic, @post], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this post?' } %>
  <% end %>
     <div>
     <h3><%= pluralize(@post.points, 'point') %></h3>
     <small>
       <%= pluralize(@post.up_votes, 'up vote') %>,
       <%= pluralize(@post.down_votes, 'down vote') %>
     </small>
     <%= render partial: 'favorites/favorite', locals: { post: @post } %>
   </div>
  </div>
  <div class="col-md-8">
    <%= render partial: 'votes/voter', locals: { post: @post } %>
    <h1><%= @post.markdown_title %></h1>      
  </div>
</div>
<div class="row">
  <div class="col-md-4">
       <%= image_tag(@post.image.full.url) if @post.image? %>
  </div>
  <div class="col-md-8">
    <p><%= @post.markdown_body %></p>
    <br> 
    <h6> submitted <%= time_ago_in_words(@post.created_at) %> ago by
       <%= @post.user.name %></h6>
  </div>
  
</div>
<div class="row">
  <div class="col-md-4"> 
    
    
  </div>
</div>

<div class = "row"> 


  <div class="col-md-2"> <!-- Summary Button Begins-->
    <% if @summary != nil %>
      <p>Summary: <%= @post.summary.title %></p>
      <% if policy(Summary.new).edit? %> 
        <%= link_to "Edit summary", edit_post_summary_path(@post,@summary), class: "btn btn-success" %> 
      <% end %> 
    <% else %>
      <% if policy(Summary.new).new? %>
        <%= link_to "Summarize", new_post_summary_path(@post,@summary), class: "btn btn-success" %> 
      <% end %> 
    <% end %> 
  </div><!-- Summary Button Ends.  -->
  <div class="col-md-2">
    <%if policy(Comment.new).create?%> 
      <%= link_to "Comment", new_post_comment_path(@post,@comment), class: 'btn btn-warning' %> 
    <% end %>
  </div>

</div> 


<div class = "row"> 


  <div class="col-md-4">
  </div>

  <div class="col-md-8">
    <h2>Comments</h2>
     <div class='js-comments'>
       <%= render partial: 'comments/comment', collection: @comments %>
     </div>
     <div class='new-comment'>
       <%= render 'comments/form' %>
     </div>
  </div>
</div>

</div>